import { Lesson } from "./types";
import {
  completeCurrentStep,
  getProgress,
} from "./progress";

export function unlockNextLesson(
  roadmap: string[],
  previous: Lesson
): Lesson | null {
  const progress = completeCurrentStep();

  const nextIndex = progress.currentStep - 1;

  if (nextIndex >= roadmap.length) {
    return null;
  }

  return {
    step: progress.currentStep,

    title: roadmap[nextIndex],

    whatYouLearn:
      "This lesson will be generated by Gemini.",

    whyImportant:
      "Understanding this concept is required before moving on.",

    whatToDo: [
      "Follow the lesson.",
      "Complete the exercises.",
      "Ask questions if needed.",
    ],

    miniTask:
      "Finish this lesson and press Done.",
  };
}

export function currentStep() {
  return getProgress().currentStep;
}